global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9091"]  # Prometheus itself

  - job_name: "jenkins"
    metrics_path: "/prom/"  # Corrected path
    static_configs:
      - targets: ["13.250.54.79:9000"]  # Jenkins public IP with correct port
